SOURCES  := ../lib/list.c ../lib/mt19937ar.c ../lib/pair.c ../lib/queue.c \
            ../lib/random.c ../lib/thread.c ../lib/vector.c \
            coordinate.c grid.c labyrinth.c maze.c router.c

CXXFLAGS += -DUSE_EARLY_RELEASE

-include ../Makefile.rules
