##################################################
# Begin declarations specific to this folder
##################################################

# specify the names of the files in this folder that need to be compiled.  Be
# sure to just provide the filename, with no extension
PROG_SOURCES = coordinate grid labyrinth maze router

# specify the names of the files in the lib folder that need to be compiled.
# Be sure to just provide the filename, with no path or extension
LIB_SOURCES  = list mt19937ar pair queue random thread vector 

# specify the name of the executable to produce
PROGNAME     = labyrinth

# specify any custom build flags
CUSTOM_CXXFLAGS = -DUSE_EARLY_RELEASE
CUSTOM_LDFLAGS  = -lm
##################################################
# End of folder-specific content
##################################################

include ../Makefile.common
