##################################################
# Begin declarations specific to this folder
##################################################

# specify the names of the files in this folder that need to be compiled.  Be
# sure to just provide the filename, with no extension
PROG_SOURCES = cluster common kmeans normal

# specify the names of the files in the lib folder that need to be compiled.
# Be sure to just provide the filename, with no path or extension
LIB_SOURCES  = mt19937ar random thread

# specify the name of the executable to produce
PROGNAME     = kmeans

# specify any custom build flags
CUSTOM_CXXFLAGS = -DOUTPUT_TO_STDOUT

##################################################
# End of folder-specific content
##################################################

include ../Makefile.common
