SOURCES := ../lib/bitmap.c ../lib/hash.c ../lib/hashtable.c ../lib/pair.c \
           ../lib/random.c ../lib/list.c ../lib/mt19937ar.c ../lib/thread.c \
           ../lib/vector.c \
           gene.c genome.c segments.c sequencer.c table.c

CXXFLAGS += -DLIST_NO_DUPLICATES -DCHUNK_STEP1=12

-include ../Makefile.rules
