SOURCES  := ../lib/list.c ../lib/mt19937ar.c ../lib/pair.c ../lib/queue.c \
            ../lib/random.c ../lib/rbtree.c ../lib/thread.c ../lib/vector.c \
            decoder.c detector.c dictionary.c intruder.c packet.c \
            preprocessor.c stream.c

CXXFLAGS += -DMAP_USE_RBTREE

-include ../Makefile.rules
