SOURCES  := ../lib/bitmap.c ../lib/list.c ../lib/mt19937ar.c ../lib/queue.c \
            ../lib/random.c ../lib/thread.c ../lib/vector.c \
            adtree.c bayes.c data.c learner.c net.c sort.c

CXXFLAGS += -DLIST_NO_DUPLICATES -DLEARNER_TRY_REMOVE -DLEARNER_TRY_REVERSE

-include ../Makefile.rules
