SOURCES  := ../lib/pair.c ../lib/mt19937ar.c ../lib/random.c ../lib/thread.c \
            ../lib/list.c ../lib/rbtree.c \
            client.c customer.c manager.c reservation.c vacation.c

CXXFLAGS += -DLIST_NO_DUPLICATES -DMAP_USE_RBTREE

-include ../Makefile.rules
